spring:
    application:
        name: edunet
    profiles:
        include: db
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        cache: false
    devtools: 
        livereload:
            enabled: true
            port: 35729
    freemarker:
        cache: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: your@gmail.com
        password: app-password      # Gmail은 ‘앱 비밀번호’ 사용
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
        